### ISSUE TITLE
filecr.com is confirmed to be spreading malware

### ISSUE THREAD

**Issue by lassethomsen1** [hijoput4/SharingWare#1]
filecr.com links should be removed because they are spreading malware

**Comment by hijoput4** [comment]
Post your evidence. It must NOT be a simple post on a random webpage, it must be REAL evidence.

**Comment by hijoput4** [comment]
No response. I've been using File.cr without any problems. Check if you have a proper adblocker when entering their page.

**Comment by TechMorgan** [comment]
> Post your evidence. It must NOT be a simple post on a random webpage, it must be REAL evidence.

https://rentry.co/filecr_malware

**Comment by hijoput4** [comment]
last time I checked that rentry post made by who-knows, I didn't have what he says I must have to be infected, and I downloaded and installed many softwares from filecr.

If you are concerned, do not use it or bring new (this thing is old, and I found it by myself) evidence that is not a mess to read. The guy is also giving "samples", you should get yours and analyze them if in doubt, but do not download his samples as they could be altered. 

You see, internet is a jungle. You can't trust any random guy. Nobody else came with those "investigations" and nobody enforced that view on a widespread site like filecr, meaning this is not what most people think or felt. 

There are federal agents using malware to infect and spy, there are internet rats trying to install miners on noobs pcs, there are disgruntled people trying to kill the fun for others (you know, those who go to the church every sunday and think cracked software will send them to hell [ironic]) and there are users that are created just to sow fear amongst noobs, to defend their softwares or at least avenge the fact that their software is being shared online for free.

Any of these could be true, including filecr really spreading malware. 
So until I see trustworthy proof of this, I'm not taking the link down.
